name: Static code analysis

on:
  push:
    tags:
      - static

jobs:
  static-analysis:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: install clang-tools and clang
      run: |
        sudo apt-get update
        sudo apt-get install -y clang clang-tools
        sudo apt-get install -y build-essential libx11-dev libglfw3-dev
        sudo apt-get install -y libglfw3 xorg-dev cmake

    - name: Run clang static analyzer
      run: scan-build -v make

    - name: Upload scan-build results
      uses: actions/upload-artifact@v3
      with:
        name: scan-build-result
        path: /tmp/scan-build*
